#!/usr/bin/env python3
import json
import re

# Read the consolidated meals
consolidated_meals = {
    "breakfast": [
        {"id":"b1","name":"Scrambled Eggs with Spinach & Cherry Tomatoes","cal":290,"protein":28,"carbs":8,"fat":15,"prepTime":8,"goals":["lose","definition","maintenance"],"ingredients":[{"item":"Large eggs","amount":4,"unit":"whole","cat":"protein"},{"item":"Spinach","amount":80,"unit":"g","cat":"vegetables"},{"item":"Cherry tomatoes","amount":100,"unit":"g","cat":"vegetables"},{"item":"Olive oil","amount":1,"unit":"tsp","cat":"pantry"},{"item":"Salt & pepper","amount":1,"unit":"pinch","cat":"pantry"}],"recipe":["Heat olive oil in a non-stick pan over medium heat.","Add spinach and cherry tomatoes. Sauté 2 minutes until tomatoes blister.","Whisk eggs with salt and pepper. Pour into pan.","Fold gently until eggs are just set (2-3 min). Serve immediately."]},
        {"id":"b2","name":"Greek Yogurt Parfait with Berries & Granola","cal":345,"protein":25,"carbs":54,"fat":4,"prepTime":5,"goals":["lose","maintenance","definition"],"ingredients":[{"item":"Greek yogurt","amount":200,"unit":"g","cat":"dairy"},{"item":"Frozen mixed berries","amount":100,"unit":"g","cat":"vegetables"},{"item":"Granola","amount":30,"unit":"g","cat":"grains"},{"item":"Honey","amount":1.5,"unit":"tbsp","cat":"pantry"}],"recipe":["Spoon yogurt into a bowl. Top with half the berries.","Drizzle with half the honey. Add granola on top.","Add remaining berries and honey. Serve immediately."]},
        {"id":"b3","name":"Protein Oatmeal with Banana & Honey","cal":520,"protein":35,"carbs":82,"fat":8,"prepTime":8,"goals":["build","maintenance"],"ingredients":[{"item":"Rolled oats","amount":80,"unit":"g","cat":"grains"},{"item":"Protein powder","amount":30,"unit":"g","cat":"protein"},{"item":"Banana","amount":1,"unit":"medium","cat":"vegetables"},{"item":"Almond milk","amount":250,"unit":"ml","cat":"dairy"},{"item":"Honey","amount":1,"unit":"tbsp","cat":"pantry"}],"recipe":["Heat almond milk in a saucepan over medium heat.","Stir in oats and cook 4-5 minutes until creamy.","Remove from heat. Stir in protein powder until dissolved.","Top with banana slices and drizzle with honey. Serve warm."]},
        {"id":"b4","name":"Veggie Omelette with Feta","cal":380,"protein":30,"carbs":9,"fat":24,"prepTime":10,"goals":["lose","definition","maintenance"],"ingredients":[{"item":"Large eggs","amount":4,"unit":"whole","cat":"protein"},{"item":"Spinach","amount":60,"unit":"g","cat":"vegetables"},{"item":"Bell peppers","amount":0.5,"unit":"whole","cat":"vegetables"},{"item":"Feta cheese","amount":30,"unit":"g","cat":"dairy"},{"item":"Olive oil","amount":1,"unit":"tsp","cat":"pantry"},{"item":"Salt & pepper","amount":1,"unit":"pinch","cat":"pantry"}],"recipe":["Whisk eggs with salt and pepper.","Heat olive oil in a non-stick pan over medium heat.","Sauté diced peppers and spinach for 2 minutes.","Pour in eggs. Let set 90 seconds, then fold in half with feta cheese on one side.","Slide onto plate and serve immediately."]},
        {"id":"b5","name":"Berry Smoothie Bowl with Granola","cal":410,"protein":32,"carbs":50,"fat":10,"prepTime":8,"goals":["build","lose","definition"],"ingredients":[{"item":"Frozen mixed berries","amount":120,"unit":"g","cat":"vegetables"},{"item":"Protein powder","amount":30,"unit":"g","cat":"protein"},{"item":"Almond milk","amount":80,"unit":"ml","cat":"dairy"},{"item":"Greek yogurt","amount":100,"unit":"g","cat":"dairy"},{"item":"Granola","amount":25,"unit":"g","cat":"grains"},{"item":"Chia seeds","amount":10,"unit":"g","cat":"pantry"}],"recipe":["Add frozen berries, protein powder, almond milk, and Greek yogurt to blender.","Blend until thick and smooth (not pourable).","Pour into bowl. Top with granola and chia seeds.","Eat immediately with a spoon before it melts."]},
        {"id":"b6","name":"Cottage Cheese Bowl with Berries & Walnuts","cal":310,"protein":30,"carbs":24,"fat":12,"prepTime":3,"goals":["lose","definition","maintenance"],"ingredients":[{"item":"Cottage cheese","amount":250,"unit":"g","cat":"dairy"},{"item":"Frozen mixed berries","amount":80,"unit":"g","cat":"vegetables"},{"item":"Walnuts","amount":15,"unit":"g","cat":"pantry"},{"item":"Honey","amount":1,"unit":"tsp","cat":"pantry"}],"recipe":["Spoon cottage cheese into a bowl.","Top with berries and crushed walnuts.","Drizzle with honey and serve chilled."]},
        {"id":"b7","name":"Breakfast Burrito with Eggs & Turkey","cal":520,"protein":42,"carbs":38,"fat":20,"prepTime":12,"goals":["build","maintenance"],"ingredients":[{"item":"Large eggs","amount":3,"unit":"whole","cat":"protein"},{"item":"Turkey mince","amount":80,"unit":"g","cat":"protein"},{"item":"Whole wheat bread","amount":2,"unit":"slices","cat":"grains"},{"item":"Cheddar cheese","amount":25,"unit":"g","cat":"dairy"},{"item":"Cherry tomatoes","amount":50,"unit":"g","cat":"vegetables"},{"item":"Olive oil","amount":1,"unit":"tsp","cat":"pantry"},{"item":"Salt & pepper","amount":1,"unit":"pinch","cat":"pantry"}],"recipe":["Brown turkey mince in a pan over medium heat (5 min). Set aside.","Lightly toast bread. Whisk and scramble eggs (2 min).","Layer: turkey, eggs, tomatoes, cheese on bread.","Roll up or fold in half. Serve warm."]},
        {"id":"b8","name":"Protein Pancakes with Peanut Butter","cal":480,"protein":38,"carbs":40,"fat":16,"prepTime":10,"goals":["build","maintenance","definition"],"ingredients":[{"item":"Eggs","amount":3,"unit":"whole","cat":"protein"},{"item":"Rolled oats","amount":40,"unit":"g","cat":"grains"},{"item":"Protein powder","amount":20,"unit":"g","cat":"protein"},{"item":"Banana","amount":0.5,"unit":"whole","cat":"vegetables"},{"item":"Peanut butter","amount":2,"unit":"tbsp","cat":"pantry"},{"item":"Honey","amount":1,"unit":"tsp","cat":"pantry"}],"recipe":["Blend eggs, oats, protein powder, and banana into smooth batter.","Cook on non-stick pan: 2-3 min per side until golden.","Top with peanut butter and honey. Serve warm."]},
        {"id":"b9","name":"Pasta Carbonara Breakfast","cal":510,"protein":28,"carbs":52,"fat":22,"prepTime":10,"goals":["build","maintenance"],"ingredients":[{"item":"Whole wheat pasta","amount":100,"unit":"g","cat":"grains"},{"item":"Eggs","amount":2,"unit":"whole","cat":"protein"},{"item":"Parmesan cheese","amount":30,"unit":"g","cat":"dairy"},{"item":"Onion","amount":30,"unit":"g","cat":"vegetables"},{"item":"Olive oil","amount":1.5,"unit":"tsp","cat":"pantry"},{"item":"Salt & pepper","amount":1,"unit":"pinch","cat":"pantry"}],"recipe":["Cook pasta according to package directions. Drain and set aside.","Sauté diced onion in olive oil until soft (3 min).","Whisk eggs with parmesan. Add hot pasta to pan with onion.","Remove from heat and quickly stir in egg mixture to coat (creates creamy sauce).","Season with salt and pepper. Serve immediately."]},
        {"id":"b10","name":"Rice Cakes with Almond Butter & Banana","cal":350,"protein":10,"carbs":48,"fat":14,"prepTime":3,"goals":["maintenance","lose"],"ingredients":[{"item":"Rice cakes","amount":2,"unit":"whole","cat":"grains"},{"item":"Almond butter","amount":2,"unit":"tbsp","cat":"pantry"},{"item":"Banana","amount":1,"unit":"medium","cat":"vegetables"},{"item":"Honey","amount":1,"unit":"tsp","cat":"pantry"},{"item":"Cinnamon","amount":0.25,"unit":"tsp","cat":"pantry"}],"recipe":["Spread almond butter on rice cakes.","Top with banana slices.","Drizzle with honey and sprinkle cinnamon.","Serve immediately."]}
    ],
    "lunch": [
        {"id":"l1","name":"Grilled Salmon with Brown Rice & Broccoli","cal":580,"protein":48,"carbs":60,"fat":15,"prepTime":20,"goals":["build","maintenance"],"ingredients":[{"item":"Salmon fillet","amount":150,"unit":"g","cat":"protein"},{"item":"Brown rice","amount":150,"unit":"g cooked","cat":"grains"},{"item":"Broccoli","amount":150,"unit":"g","cat":"vegetables"},{"item":"Olive oil","amount":1.5,"unit":"tsp","cat":"pantry"},{"item":"Lemon","amount":0.5,"unit":"whole","cat":"vegetables"},{"item":"Salt & pepper","amount":1,"unit":"pinch","cat":"pantry"}],"recipe":["Season salmon with salt, pepper, and lemon juice.","Grill or pan-sear salmon 4 min per side until cooked through.","Steam broccoli 5-7 minutes until tender-crisp.","Drizzle salmon and broccoli with olive oil. Serve with brown rice."]},
        {"id":"l2","name":"Chicken Brown Rice Bowl with Cherry Tomatoes","cal":520,"protein":52,"carbs":54,"fat":10,"prepTime":20,"goals":["build","maintenance","lose"],"ingredients":[{"item":"Chicken breast","amount":150,"unit":"g","cat":"protein"},{"item":"Brown rice","amount":150,"unit":"g cooked","cat":"grains"},{"item":"Cherry tomatoes","amount":120,"unit":"g","cat":"vegetables"},{"item":"Onion","amount":40,"unit":"g","cat":"vegetables"},{"item":"Olive oil","amount":1,"unit":"tsp","cat":"pantry"},{"item":"Salt & pepper","amount":1,"unit":"pinch","cat":"pantry"}],"recipe":["Season and grill chicken 6-8 min per side until cooked (165°F).","Sauté diced onion and cherry tomatoes in olive oil (3 min).","Slice chicken. Serve with brown rice and tomato mixture on top."]},
        {"id":"l3","name":"Turkey Meatballs with Brown Rice","cal":420,"protein":45,"carbs":42,"fat":12,"prepTime":22,"goals":["lose","definition","maintenance"],"ingredients":[{"item":"Turkey mince","amount":150,"unit":"g","cat":"protein"},{"item":"Brown rice","amount":100,"unit":"g cooked","cat":"grains"},{"item":"Broccoli","amount":120,"unit":"g","cat":"vegetables"},{"item":"Onion","amount":30,"unit":"g","cat":"vegetables"},{"item":"Olive oil","amount":1,"unit":"tsp","cat":"pantry"},{"item":"Salt & pepper","amount":1,"unit":"pinch","cat":"pantry"}],"recipe":["Mix turkey with minced onion, salt, and pepper. Form 8-10 meatballs.","Bake at 200°C for 15 minutes until cooked through.","Steam broccoli 5 minutes. Serve with brown rice and meatballs."]},
        {"id":"l4","name":"Whole Wheat Pasta with Chicken & Tomato Sauce","cal":510,"protein":48,"carbs":56,"fat":10,"prepTime":20,"goals":["build","maintenance"],"ingredients":[{"item":"Whole wheat pasta","amount":100,"unit":"g dry","cat":"grains"},{"item":"Chicken breast","amount":120,"unit":"g","cat":"protein"},{"item":"Passata tomato sauce","amount":150,"unit":"ml","cat":"pantry"},{"item":"Onion","amount":40,"unit":"g","cat":"vegetables"},{"item":"Olive oil","amount":1.5,"unit":"tsp","cat":"pantry"},{"item":"Garlic","amount":2,"unit":"cloves","cat":"pantry"},{"item":"Salt & pepper","amount":1,"unit":"pinch","cat":"pantry"}],"recipe":["Cook pasta according to package directions. Drain.","Dice and pan-sear chicken until cooked (8 min). Set aside.","Sauté minced garlic and onion in olive oil (2 min).","Add passata sauce and simmer 5 minutes.","Mix in pasta and chicken. Toss well. Season with salt and pepper."]},
        {"id":"l5","name":"Asian Chicken Stir-Fry with Brown Rice","cal":540,"protein":50,"carbs":58,"fat":12,"prepTime":15,"goals":["build","lose","maintenance"],"ingredients":[{"item":"Chicken breast","amount":140,"unit":"g","cat":"protein"},{"item":"Brown rice","amount":150,"unit":"g cooked","cat":"grains"},{"item":"Broccoli","amount":100,"unit":"g","cat":"vegetables"},{"item":"Bell peppers","amount":100,"unit":"g","cat":"vegetables"},{"item":"Onion","amount":40,"unit":"g","cat":"vegetables"},{"item":"Soy sauce","amount":2,"unit":"tbsp","cat":"pantry"},{"item":"Sesame oil","amount":1,"unit":"tsp","cat":"pantry"},{"item":"Garlic","amount":2,"unit":"cloves","cat":"pantry"},{"item":"Ginger","amount":5,"unit":"g","cat":"pantry"}],"recipe":["Dice chicken and vegetables.","Heat sesame oil in a wok or large pan over high heat.","Stir-fry chicken until mostly cooked (4 min). Remove and set aside.","Add vegetables and minced garlic/ginger. Stir-fry 3-4 minutes.","Return chicken, add soy sauce. Toss 1 minute.","Serve over brown rice."]},
        {"id":"l6","name":"Canned Tuna Salad with Brown Rice","cal":420,"protein":42,"carbs":48,"fat":8,"prepTime":8,"goals":["lose","definition","maintenance"],"ingredients":[{"item":"Canned tuna in water","amount":140,"unit":"g drained","cat":"protein"},{"item":"Brown rice","amount":120,"unit":"g cooked","cat":"grains"},{"item":"Cherry tomatoes","amount":100,"unit":"g","cat":"vegetables"},{"item":"Cucumber","amount":100,"unit":"g","cat":"vegetables"},{"item":"Mixed greens","amount":80,"unit":"g","cat":"vegetables"},{"item":"Olive oil","amount":1,"unit":"tbsp","cat":"pantry"},{"item":"Lemon juice","amount":1,"unit":"tbsp","cat":"pantry"},{"item":"Salt & pepper","amount":1,"unit":"pinch","cat":"pantry"}],"recipe":["Mix drained tuna with diced tomatoes and cucumber.","Dress with olive oil, lemon juice, salt, and pepper.","Serve tuna mixture over brown rice bed with mixed greens on side."]},
        {"id":"l7","name":"Salmon Pasta with Garlic & Olive Oil","cal":530,"protein":40,"carbs":58,"fat":14,"prepTime":15,"goals":["build","maintenance"],"ingredients":[{"item":"Whole wheat pasta","amount":100,"unit":"g dry","cat":"grains"},{"item":"Salmon fillet","amount":120,"unit":"g","cat":"protein"},{"item":"Cherry tomatoes","amount":80,"unit":"g","cat":"vegetables"},{"item":"Olive oil","amount":2,"unit":"tsp","cat":"pantry"},{"item":"Garlic","amount":3,"unit":"cloves","cat":"pantry"},{"item":"Lemon","amount":0.5,"unit":"whole","cat":"vegetables"},{"item":"Salt & pepper","amount":1,"unit":"pinch","cat":"pantry"}],"recipe":["Cook pasta according to package directions. Drain.","Pan-sear salmon until cooked (4 min per side). Flake into chunks.","In same pan, sauté minced garlic in olive oil (1 min).","Add halved cherry tomatoes and cook 2 minutes.","Toss pasta with salmon mixture. Squeeze lemon juice over top."]},
        {"id":"l8","name":"Grilled Chicken Sandwich on Rice Cakes","cal":380,"protein":48,"carbs":32,"fat":10,"prepTime":12,"goals":["lose","definition","maintenance"],"ingredients":[{"item":"Chicken breast","amount":140,"unit":"g","cat":"protein"},{"item":"Rice cakes","amount":2,"unit":"whole","cat":"grains"},{"item":"Cherry tomatoes","amount":50,"unit":"g","cat":"vegetables"},{"item":"Cucumber","amount":50,"unit":"g","cat":"vegetables"},{"item":"Mixed greens","amount":40,"unit":"g","cat":"vegetables"},{"item":"Olive oil","amount":0.5,"unit":"tbsp","cat":"pantry"},{"item":"Lemon","amount":0.25,"unit":"whole","cat":"pantry"},{"item":"Salt & pepper","amount":1,"unit":"pinch","cat":"pantry"}],"recipe":["Grill seasoned chicken breast 6-8 minutes per side until cooked.","Slice thinly.","Layer rice cakes with greens, tomatoes, cucumber, and chicken.","Drizzle with olive oil and lemon. Serve immediately."]},
        {"id":"l9","name":"Whole Wheat Pasta Primavera","cal":420,"protein":18,"carbs":66,"fat":10,"prepTime":15,"goals":["lose","maintenance"],"ingredients":[{"item":"Whole wheat pasta","amount":100,"unit":"g dry","cat":"grains"},{"item":"Broccoli","amount":80,"unit":"g","cat":"vegetables"},{"item":"Bell peppers","amount":80,"unit":"g","cat":"vegetables"},{"item":"Cherry tomatoes","amount":80,"unit":"g","cat":"vegetables"},{"item":"Zucchini","amount":80,"unit":"g","cat":"vegetables"},{"item":"Olive oil","amount":1.5,"unit":"tbsp","cat":"pantry"},{"item":"Garlic","amount":2,"unit":"cloves","cat":"pantry"},{"item":"Parmesan cheese","amount":20,"unit":"g","cat":"dairy"},{"item":"Salt & pepper","amount":1,"unit":"pinch","cat":"pantry"}],"recipe":["Cook pasta according to package directions. Drain.","In a large pan, sauté minced garlic in olive oil (1 min).","Add all chopped vegetables. Stir-fry 5-6 minutes until tender-crisp.","Toss pasta with vegetables. Top with parmesan. Season and serve."]},
        {"id":"l10","name":"Whole Wheat Pasta with Tuna & Cherry Tomatoes","cal":450,"protein":38,"carbs":54,"fat":10,"prepTime":12,"goals":["lose","definition","maintenance"],"ingredients":[{"item":"Whole wheat pasta","amount":100,"unit":"g dry","cat":"grains"},{"item":"Canned tuna","amount":120,"unit":"g","cat":"protein"},{"item":"Cherry tomatoes","amount":100,"unit":"g","cat":"vegetables"},{"item":"Olive oil","amount":1.5,"unit":"tbsp","cat":"pantry"},{"item":"Garlic","amount":2,"unit":"cloves","cat":"pantry"},{"item":"Lemon","amount":0.5,"unit":"whole","cat":"pantry"},{"item":"Parmesan cheese","amount":20,"unit":"g","cat":"dairy"},{"item":"Salt & pepper","amount":1,"unit":"pinch","cat":"pantry"}],"recipe":["Cook pasta. Drain and set aside.","In a large pan, sauté minced garlic in olive oil (1 min).","Add halved cherry tomatoes. Cook 2 minutes.","Gently fold in drained tuna and cooked pasta.","Squeeze lemon juice over top. Toss gently. Top with parmesan."]},
        {"id":"l11","name":"Asian Chicken Bowl with Rice","cal":480,"protein":48,"carbs":52,"fat":10,"prepTime":18,"goals":["build","lose","maintenance"],"ingredients":[{"item":"Chicken breast","amount":140,"unit":"g","cat":"protein"},{"item":"Brown rice","amount":140,"unit":"g cooked","cat":"grains"},{"item":"Broccoli","amount":120,"unit":"g","cat":"vegetables"},{"item":"Soy sauce","amount":2,"unit":"tbsp","cat":"pantry"},{"item":"Sesame oil","amount":0.5,"unit":"tsp","cat":"pantry"},{"item":"Garlic","amount":2,"unit":"cloves","cat":"pantry"},{"item":"Ginger","amount":5,"unit":"g","cat":"pantry"}],"recipe":["Dice chicken and steam broccoli.","Pan-sear diced chicken in sesame oil with minced garlic/ginger (5 min).","Add broccoli and soy sauce. Toss 2 minutes.","Serve over brown rice."]}
    ],
    "dinner": [
        {"id":"d1","name":"Grilled Salmon with Brown Rice & Vegetables","cal":620,"protein":50,"carbs":62,"fat":16,"prepTime":22,"goals":["build","maintenance"],"ingredients":[{"item":"Salmon fillet","amount":160,"unit":"g","cat":"protein"},{"item":"Brown rice","amount":160,"unit":"g cooked","cat":"grains"},{"item":"Broccoli","amount":150,"unit":"g","cat":"vegetables"},{"item":"Onion","amount":40,"unit":"g","cat":"vegetables"},{"item":"Olive oil","amount":2,"unit":"tsp","cat":"pantry"},{"item":"Lemon","amount":0.5,"unit":"whole","cat":"vegetables"},{"item":"Salt & pepper","amount":1,"unit":"pinch","cat":"pantry"}],"recipe":["Preheat oven to 200°C.","Season salmon with salt, pepper, and lemon juice.","Bake salmon 12-15 minutes until cooked through.","Steam broccoli 5-7 minutes.","Sauté diced onion in olive oil. Serve with brown rice and vegetables."]},
        {"id":"d2","name":"Grilled Chicken with Sweet Potato & Broccoli","cal":580,"protein":52,"carbs":64,"fat":12,"prepTime":25,"goals":["build","maintenance","lose"],"ingredients":[{"item":"Chicken breast","amount":160,"unit":"g","cat":"protein"},{"item":"Sweet potato","amount":200,"unit":"g","cat":"vegetables"},{"item":"Broccoli","amount":140,"unit":"g","cat":"vegetables"},{"item":"Olive oil","amount":1.5,"unit":"tsp","cat":"pantry"},{"item":"Garlic","amount":2,"unit":"cloves","cat":"pantry"},{"item":"Salt & pepper","amount":1,"unit":"pinch","cat":"pantry"}],"recipe":["Cut sweet potato into cubes. Roast at 200°C for 18 minutes.","Season and grill chicken 6-8 minutes per side.","Steam broccoli 5-7 minutes.","Toss roasted sweet potato with olive oil and minced garlic.","Plate chicken with roasted potato and steamed broccoli."]},
        {"id":"d3","name":"Lean Beef Steak with Brown Rice","cal":590,"protein":54,"carbs":58,"fat":14,"prepTime":20,"goals":["build","maintenance"],"ingredients":[{"item":"Lean beef strips","amount":160,"unit":"g","cat":"protein"},{"item":"Brown rice","amount":150,"unit":"g cooked","cat":"grains"},{"item":"Bell peppers","amount":100,"unit":"g","cat":"vegetables"},{"item":"Onion","amount":50,"unit":"g","cat":"vegetables"},{"item":"Olive oil","amount":1.5,"unit":"tsp","cat":"pantry"},{"item":"Salt & pepper","amount":1,"unit":"pinch","cat":"pantry"}],"recipe":["Season beef strips with salt and pepper.","Sear in hot pan 2-3 minutes per side until cooked to preference.","Remove beef. Sauté peppers and onion in same pan 5 minutes.","Return beef to pan and toss. Serve with brown rice."]},
        {"id":"d4","name":"Turkey Meatballs with Zucchini Noodles","cal":400,"protein":50,"carbs":18,"fat":14,"prepTime":25,"goals":["lose","definition","maintenance"],"ingredients":[{"item":"Turkey mince","amount":160,"unit":"g","cat":"protein"},{"item":"Zucchini","amount":200,"unit":"g","cat":"vegetables"},{"item":"Passata tomato sauce","amount":150,"unit":"ml","cat":"pantry"},{"item":"Onion","amount":40,"unit":"g","cat":"vegetables"},{"item":"Olive oil","amount":1.5,"unit":"tbsp","cat":"pantry"},{"item":"Garlic","amount":2,"unit":"cloves","cat":"pantry"},{"item":"Salt & pepper","amount":1,"unit":"pinch","cat":"pantry"}],"recipe":["Form turkey mince into 10-12 meatballs with minced onion.","Bake at 200°C for 15 minutes until cooked.","Spiralize zucchini or use a peeler to create noodles.","Sauté garlic in olive oil (1 min). Add passata and simmer 3 minutes.","Toss zucchini noodles gently with sauce and top with meatballs."]},
        {"id":"d5","name":"Whole Wheat Pasta with Chicken Marinara","cal":550,"protein":50,"carbs":62,"fat":12,"prepTime":20,"goals":["build","maintenance"],"ingredients":[{"item":"Whole wheat pasta","amount":110,"unit":"g dry","cat":"grains"},{"item":"Chicken breast","amount":140,"unit":"g","cat":"protein"},{"item":"Passata tomato sauce","amount":180,"unit":"ml","cat":"pantry"},{"item":"Onion","amount":50,"unit":"g","cat":"vegetables"},{"item":"Garlic","amount":3,"unit":"cloves","cat":"pantry"},{"item":"Olive oil","amount":1,"unit":"tbsp","cat":"pantry"},{"item":"Parmesan cheese","amount":25,"unit":"g","cat":"dairy"},{"item":"Salt & pepper","amount":1,"unit":"pinch","cat":"pantry"}],"recipe":["Cook pasta. Drain.","Dice and pan-sear chicken until cooked (8 min). Set aside.","Sauté minced garlic and diced onion in olive oil (2 min).","Add passata and simmer 5 minutes.","Mix in pasta and chicken. Top with parmesan and serve."]},
        {"id":"d6","name":"Pan-Seared Salmon with Vegetables","cal":520,"protein":48,"carbs":28,"fat":20,"prepTime":18,"goals":["build","lose","maintenance"],"ingredients":[{"item":"Salmon fillet","amount":160,"unit":"g","cat":"protein"},{"item":"Bell peppers","amount":100,"unit":"g","cat":"vegetables"},{"item":"Zucchini","amount":100,"unit":"g","cat":"vegetables"},{"item":"Onion","amount":40,"unit":"g","cat":"vegetables"},{"item":"Olive oil","amount":2,"unit":"tsp","cat":"pantry"},{"item":"Lemon","amount":0.5,"unit":"whole","cat":"pantry"},{"item":"Garlic","amount":2,"unit":"cloves","cat":"pantry"},{"item":"Salt & pepper","amount":1,"unit":"pinch","cat":"pantry"}],"recipe":["Heat olive oil in large pan. Season salmon and pan-sear 4 min per side.","Remove salmon. Add diced vegetables and minced garlic to pan.","Sauté vegetables 5-6 minutes until tender.","Return salmon to pan. Squeeze lemon juice over top and serve."]},
        {"id":"d7","name":"Asian Chicken with Brown Rice","cal":560,"protein":54,"carbs":58,"fat":12,"prepTime":20,"goals":["build","maintenance","lose"],"ingredients":[{"item":"Chicken breast","amount":160,"unit":"g","cat":"protein"},{"item":"Brown rice","amount":160,"unit":"g cooked","cat":"grains"},{"item":"Bell peppers","amount":100,"unit":"g","cat":"vegetables"},{"item":"Broccoli","amount":100,"unit":"g","cat":"vegetables"},{"item":"Soy sauce","amount":2.5,"unit":"tbsp","cat":"pantry"},{"item":"Sesame oil","amount":1,"unit":"tsp","cat":"pantry"},{"item":"Garlic","amount":3,"unit":"cloves","cat":"pantry"},{"item":"Ginger","amount":6,"unit":"g","cat":"pantry"}],"recipe":["Dice chicken and stir-fry in sesame oil with minced garlic/ginger (5 min).","Add chopped vegetables. Stir-fry 4 minutes.","Add soy sauce and toss 1 minute.","Serve over brown rice."]},
        {"id":"d8","name":"Lean Beef Stir-Fry with Brown Rice","cal":550,"protein":52,"carbs":54,"fat":14,"prepTime":18,"goals":["build","maintenance","lose"],"ingredients":[{"item":"Lean beef strips","amount":160,"unit":"g","cat":"protein"},{"item":"Brown rice","amount":140,"unit":"g cooked","cat":"grains"},{"item":"Broccoli","amount":120,"unit":"g","cat":"vegetables"},{"item":"Bell peppers","amount":80,"unit":"g","cat":"vegetables"},{"item":"Onion","amount":40,"unit":"g","cat":"vegetables"},{"item":"Soy sauce","amount":2,"unit":"tbsp","cat":"pantry"},{"item":"Garlic","amount":2,"unit":"cloves","cat":"pantry"},{"item":"Sesame oil","amount":0.5,"unit":"tsp","cat":"pantry"}],"recipe":["Sear beef strips in sesame oil until cooked (3-4 min). Remove and set aside.","Stir-fry vegetables and minced garlic 5 minutes.","Return beef, add soy sauce, toss 1 minute.","Serve over brown rice."]},
        {"id":"d9","name":"Ground Turkey with Sweet Potato & Vegetables","cal":540,"protein":50,"carbs":60,"fat":12,"prepTime":22,"goals":["build","maintenance"],"ingredients":[{"item":"Turkey mince","amount":160,"unit":"g","cat":"protein"},{"item":"Sweet potato","amount":180,"unit":"g","cat":"vegetables"},{"item":"Spinach","amount":100,"unit":"g","cat":"vegetables"},{"item":"Onion","amount":50,"unit":"g","cat":"vegetables"},{"item":"Olive oil","amount":1.5,"unit":"tsp","cat":"pantry"},{"item":"Garlic","amount":2,"unit":"cloves","cat":"pantry"},{"item":"Salt & pepper","amount":1,"unit":"pinch","cat":"pantry"}],"recipe":["Cube sweet potato and roast at 200°C for 15 minutes.","Brown turkey mince in a pan (5 min). Set aside.","Sauté minced garlic and diced onion (2 min).","Add spinach and cook 2 minutes until wilted.","Return turkey and roasted sweet potato. Mix and warm through."]},
        {"id":"d10","name":"Whole Wheat Pasta with Tuna & Fresh Vegetables","cal":480,"protein":42,"carbs":60,"fat":10,"prepTime":15,"goals":["lose","definition","maintenance"],"ingredients":[{"item":"Whole wheat pasta","amount":110,"unit":"g dry","cat":"grains"},{"item":"Canned tuna","amount":140,"unit":"g","cat":"protein"},{"item":"Cherry tomatoes","amount":100,"unit":"g","cat":"vegetables"},{"item":"Spinach","amount":80,"unit":"g","cat":"vegetables"},{"item":"Olive oil","amount":1.5,"unit":"tbsp","cat":"pantry"},{"item":"Garlic","amount":2,"unit":"cloves","cat":"pantry"},{"item":"Lemon","amount":0.5,"unit":"whole","cat":"pantry"},{"item":"Salt & pepper","amount":1,"unit":"pinch","cat":"pantry"}],"recipe":["Cook pasta. Drain.","In same pot, sauté minced garlic in olive oil (1 min).","Add spinach and cook until wilted (1 min).","Add halved cherry tomatoes and drained tuna. Warm through.","Toss with pasta. Squeeze lemon juice over top and serve."]}
    ],
    "snack": [
        {"id":"s1","name":"Classic Protein Smoothie","cal":220,"protein":30,"carbs":18,"fat":3,"prepTime":5,"goals":["lose","build","definition","maintenance"],"ingredients":[{"item":"Protein powder","amount":30,"unit":"g","cat":"protein"},{"item":"Almond milk","amount":200,"unit":"ml","cat":"dairy"},{"item":"Banana","amount":0.5,"unit":"medium","cat":"vegetables"},{"item":"Honey","amount":1,"unit":"tsp","cat":"pantry"}],"recipe":["Add all ingredients to blender.","Blend until smooth. Serve immediately or chill."]},
        {"id":"s2","name":"Berry Protein Smoothie","cal":240,"protein":30,"carbs":22,"fat":3,"prepTime":5,"goals":["lose","build","definition","maintenance"],"ingredients":[{"item":"Protein powder","amount":30,"unit":"g","cat":"protein"},{"item":"Frozen mixed berries","amount":100,"unit":"g","cat":"vegetables"},{"item":"Almond milk","amount":200,"unit":"ml","cat":"dairy"},{"item":"Honey","amount":1,"unit":"tsp","cat":"pantry"}],"recipe":["Combine frozen berries, protein powder, almond milk, and honey in blender.","Blend until smooth and thick. Serve immediately."]},
        {"id":"s3","name":"Peanut Butter Power Smoothie","cal":310,"protein":28,"carbs":28,"fat":10,"prepTime":5,"goals":["build","maintenance"],"ingredients":[{"item":"Protein powder","amount":25,"unit":"g","cat":"protein"},{"item":"Peanut butter","amount":1.5,"unit":"tbsp","cat":"pantry"},{"item":"Banana","amount":0.5,"unit":"medium","cat":"vegetables"},{"item":"Almond milk","amount":200,"unit":"ml","cat":"dairy"},{"item":"Honey","amount":0.5,"unit":"tsp","cat":"pantry"}],"recipe":["Blend protein powder, peanut butter, banana, almond milk, and honey until smooth.","Add extra almond milk if too thick. Serve immediately."]},
        {"id":"s4","name":"Greek Yogurt Berry Smoothie","cal":260,"protein":28,"carbs":32,"fat":4,"prepTime":5,"goals":["lose","definition","maintenance"],"ingredients":[{"item":"Greek yogurt","amount":150,"unit":"g","cat":"dairy"},{"item":"Frozen mixed berries","amount":100,"unit":"g","cat":"vegetables"},{"item":"Almond milk","amount":100,"unit":"ml","cat":"dairy"},{"item":"Honey","amount":1,"unit":"tsp","cat":"pantry"}],"recipe":["Add yogurt, frozen berries, almond milk, and honey to blender.","Blend until smooth. Add more milk if needed. Serve immediately."]},
        {"id":"s5","name":"Tropical Green Smoothie","cal":280,"protein":32,"carbs":26,"fat":4,"prepTime":5,"goals":["build","lose","definition"],"ingredients":[{"item":"Protein powder","amount":30,"unit":"g","cat":"protein"},{"item":"Frozen mixed berries","amount":80,"unit":"g","cat":"vegetables"},{"item":"Spinach","amount":40,"unit":"g","cat":"vegetables"},{"item":"Banana","amount":0.5,"unit":"medium","cat":"vegetables"},{"item":"Almond milk","amount":200,"unit":"ml","cat":"dairy"}],"recipe":["Add all ingredients to blender.","Blend until smooth and green. Serve immediately."]},
        {"id":"s6","name":"Overnight Oats Smoothie Bowl","cal":360,"protein":28,"carbs":48,"fat":8,"prepTime":5,"goals":["build","maintenance"],"ingredients":[{"item":"Rolled oats","amount":50,"unit":"g","cat":"grains"},{"item":"Protein powder","amount":25,"unit":"g","cat":"protein"},{"item":"Almond milk","amount":180,"unit":"ml","cat":"dairy"},{"item":"Frozen mixed berries","amount":80,"unit":"g","cat":"vegetables"},{"item":"Honey","amount":1,"unit":"tbsp","cat":"pantry"}],"recipe":["Mix oats, protein powder, almond milk, and honey.","Top with frozen berries.","Let sit 5 minutes. Add extra milk if needed. Serve as thick bowl."]},
        {"id":"s7","name":"Greek Yogurt with Granola & Berries","cal":280,"protein":25,"carbs":38,"fat":5,"prepTime":2,"goals":["lose","maintenance","definition"],"ingredients":[{"item":"Greek yogurt","amount":150,"unit":"g","cat":"dairy"},{"item":"Granola","amount":25,"unit":"g","cat":"grains"},{"item":"Frozen mixed berries","amount":80,"unit":"g","cat":"vegetables"}],"recipe":["Spoon yogurt into bowl.","Top with granola and frozen berries.","Serve chilled."]},
        {"id":"s8","name":"Cottage Cheese with Berries & Walnuts","cal":220,"protein":28,"carbs":14,"fat":8,"prepTime":2,"goals":["lose","definition","maintenance"],"ingredients":[{"item":"Cottage cheese","amount":200,"unit":"g","cat":"dairy"},{"item":"Frozen mixed berries","amount":60,"unit":"g","cat":"vegetables"},{"item":"Walnuts","amount":10,"unit":"g","cat":"pantry"}],"recipe":["Spoon cottage cheese into bowl.","Top with berries and crushed walnuts.","Serve chilled."]},
        {"id":"s9","name":"Apple with Almond Butter","cal":240,"protein":8,"carbs":28,"fat":12,"prepTime":2,"goals":["maintenance","lose"],"ingredients":[{"item":"Apple","amount":1,"unit":"medium","cat":"vegetables"},{"item":"Almond butter","amount":2,"unit":"tbsp","cat":"pantry"}],"recipe":["Slice apple.","Serve with almond butter for dipping.","Quick, satisfying snack."]},
        {"id":"s10","name":"String Cheese with Grapes","cal":210,"protein":14,"carbs":24,"fat":8,"prepTime":2,"goals":["maintenance","lose"],"ingredients":[{"item":"String cheese","amount":1,"unit":"whole","cat":"dairy"},{"item":"Grapes","amount":120,"unit":"g","cat":"vegetables"}],"recipe":["Enjoy string cheese with fresh grapes as a snack.","Great for on-the-go eating."]},
        {"id":"s11","name":"Rice Cakes with Peanut Butter & Berries","cal":280,"protein":10,"carbs":32,"fat":13,"prepTime":3,"goals":["maintenance","lose"],"ingredients":[{"item":"Rice cakes","amount":2,"unit":"whole","cat":"grains"},{"item":"Peanut butter","amount":2,"unit":"tbsp","cat":"pantry"},{"item":"Frozen mixed berries","amount":40,"unit":"g","cat":"vegetables"}],"recipe":["Spread peanut butter on rice cakes.","Top with frozen berries (they thaw slightly as you eat).","Serve immediately."]}
    ]
};

with open('diet-tracker.html', 'r', encoding='utf-8') as f:
    content = f.read()

# Convert to JSON format for embedding
json_meals = json.dumps(consolidated_meals, separators=(',', ':'), ensure_ascii=False)

# Find the MEALS object and replace it
pattern = r'(  breakfast: \[.*?)(\n\],\n\n// Spanish translations)'
match = re.search(pattern, content, re.DOTALL)

if match:
    # Build the new MEALS object in JavaScript format
    js_meals = "  breakfast: " + json_meals["breakfast"].replace("'", "\\'")
    print("✅ Found MEALS object to replace")
else:
    print("❌ Could not find MEALS object")

print("Use multi_replace_string_in_file to replace the meals database")
